### ISSUE TITLE
Node version restriction ?

### ISSUE THREAD

**Issue by Shuunen** [zachleat/eleventy#24]
Hi :)

I just wanted to try your lib, I installed it & tryed it on a md file of mine but got this error : 

`Eleventy requires Node version 8 or above. You’re currently using 9.2.0.`

After this not so frightening message I decided to remove this version check in  `\node_modules\eleventy-cli\cmd.js` and it finally worked well... what's the reason(s) to restrict the lib execution under node 8.x.x ?

**Comment by zachleat** [comment]
Oops that's a bug. It should whitelist 8 and above

**Comment by zachleat** [comment]
Released `0.1.9` on npm with this fix. Thank you and sorry about that!

**Comment by Shuunen** [comment]
> Thank you 
Thanks too :+1: 

> and sorry about that!
I'm not paying anything so there is no reasons to be sorry for :smile: thanks for your work & reactivity mate !
